name: Compilar ISO Wayblue

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Generar ISO con Podman
        run: |
          sudo podman run --rm --privileged \
            -v .:/build-container-installer/build \
            ghcr.io/jasonn3/build-container-installer:latest \
            ISO image ghcr.io/wayblueorg/wayfire:latest

      - name: Guardar la ISO para descargar
        uses: actions/upload-artifact@v4
        with:
          name: Wayblue-Wayfire-ISO
          path: "*.iso"
          compression-level: 0
          retention-days: 1